pipeline {

    // Instructs Jenkins to use the buildconductor docker image to run this pipeline Test
    
    agent {
        docker { 
            image 'greghodgkinson/jenkins-buildconductor-iib:edge' 
            label 'docker'
            args '-u root'
        }
        
    }

    stages {
    
        // Pull down source code from Git repo
        
       stage('Checkout Code'){
            steps {
                checkout([$class: 'GitSCM', branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, extensions: [[$class: 'RelativeTargetDirectory', relativeTargetDir: 'load']], submoduleCfg: [], userRemoteConfigs: [[url: 'https://github.com/sitaramaprasad-e/temp-convert-github-iib.git']]])
            }
          
       }   
       
       stage('Checkout .brokerFile'){
            steps {
                checkout([$class: 'GitSCM', branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, extensions: [[$class: 'RelativeTargetDirectory', relativeTargetDir: 'brokerFiles-load']], submoduleCfg: [], userRemoteConfigs: [[url: 'https://github.com/sitaramaprasad-e/brokerFiles-iib.git']]])
            }
          
       }  
       
       // Build BAR file from source code
       
        stage('Build BAR') {
            steps {
                sh "/buildconductor/iib/run-automation.sh build tempconvert TemperatureConverter" 
            }
        }   
        
  stage('Promotion') {
	steps{
    timeout(time: 1, unit: 'HOURS') {
      emailext body: "You are assigned to approve a jenkins job. Please open the link ${env.BUILD_URL} and provide your input on approval of deploying the job ${env.JOB_NAME} build ${env.BUILD_NUMBER}",
                recipientProviders: [[$class: 'DevelopersRecipientProvider'], [$class: 'RequesterRecipientProvider']],
                subject: "Jenkins Build is in wait state for approval of job ${env.JOB_NAME}, to: 'Akanksha.Pandey@prolifics.com'"
	input 'Do you approve the deployment?'

    }
	}
  }
		
        // Either override and deploy the BAR (with or without broker file), or upload it to UCD so it can be deployed from there (one of the below steps should be uncommented)
        
        stage('Override and Deploy BAR') {
         steps {
                sh "/buildconductor/iib/run-automation.sh overrideAndDeploy tempconvert na na na TEST iibuser iibuser TemperatureConverter TemperatureConverter/overrides/development.properties ../brokerFiles-load/DEV/TEST.broker"
        
          }
        }       
    }
	// Sending email notifications
	post {
        always {
            echo 'I will always say Hello again!!!'
            
            emailext body: "${currentBuild.currentResult}: Job ${env.JOB_NAME} build ${env.BUILD_NUMBER}\n More info at: ${env.BUILD_URL}",
                recipientProviders: [[$class: 'DevelopersRecipientProvider'], [$class: 'RequesterRecipientProvider']],
                subject: "Jenkins Build ${currentBuild.currentResult}: Job ${env.JOB_NAME}"
            
        }
    }
}
